title: CSE 140L FA24
description: Labwork page for CSE 140L Fall 2024
theme: just-the-docs

url: https://cse140l.github.io
color_scheme: dark

plugins:
  - jekyll-last-modified-at

last-modified-at:
  date-format: "%B %e %Y at %I:%M %p (%Z)"

#aux_links:
  #Template Repository: https://github.com/cse140l/fa24-labs
  #aux_links_new_tab: true

mermaid:
  version: "11.2.1"

last_edit_timestamp: false
gh_edit_link: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: pink
  new:
    title: New
    color: green
  note:
    title: Note
    color: grey-lt
  warning:
    title: Warning
    color: red
